FROM python:3.7

WORKDIR /test-travis
COPY . /test-travis

ENV PYTHONPATH="$PYTHONPATH:/test-travis/hello_world"

RUN pip3 install \
    -r /test-travis/requirements.txt

CMD python3 hello_world/server.py
